### ISSUE TITLE
Hi~ o(*￣▽￣*)ブ can you translate to English?

### ISSUE THREAD

**Issue by my522cn** [freedomikeppp/mitsubishi-fx5#1]
sorry i cannot understand Japanese, can you translate to English? thx!!;>

**Comment by freedomikeppp** [comment]
> sorry i cannot understand Japanese, can you translate to English? thx!!;>

Although I'm not good at English yet, I translated into English.

**Comment by my522cn** [comment]
thank you very much

**Comment by freedomikeppp** [comment]
> thank you very much

you are welcome
